Depend on underscore
```sh
$ npm i chai-fuzzy --save-dev
$ echo 'chai.use(require("chai-fuzzy"));' >> fixtures.js
$ npm test
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/robertcolburn/reflux-preload/node_modules/chai-fuzzy/index.js:32:9
    ...
```
:cry: :cry: